# Day 3 - Manipulating Tensors 

As tensors are the building blocks of AI algorithms it is very crucial to learn about them and their various methods. In this notebook we'll discover manipulations that we can do with matrices 

<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?si=uo_fIJx4HpN9rkFr&amp;list=PLi5giWKc4eO1G8oX3ft8ZuLQr4Y4idgng" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

This has been my go to playlist to understand math behind methods we'll use in this chapter

In [2]:
import torch

/Users/krishnaglodha/anaconda3/envs/aidoc/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [13]:
sample_tensor = torch.Tensor([2,3,4,1])

In [14]:
# increase each value with specific number 
sample_tensor += 10
sample_tensor

tensor([12., 13., 14., 11.])

In [15]:
# reduce each value with specific number 
sample_tensor -= 2
sample_tensor

tensor([10., 11., 12.,  9.])

In [16]:
# multiply each value with specific number 
sample_tensor *= 2
sample_tensor

tensor([20., 22., 24., 18.])

In [17]:
# divide each value with specific number 
sample_tensor /= 2
sample_tensor

tensor([10., 11., 12.,  9.])

In [18]:
# Element-wise matrix multiplication
sample_tensor * sample_tensor

tensor([100., 121., 144.,  81.])

Matrix multiplication requires the **inner dimension** of matrices to match and the resulting matrix will have shape of **outer dimension**

![alt text](https://i.pinimg.com/originals/33/40/6f/33406fb252eda556c301a6ff0ee56a92.png)

<iframe width="560" height="315" src="https://www.youtube.com/embed/kT4Mp9EdVqs?si=KHCv4WGQ1RsM_gE2" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

In [7]:
# Matrix multiplication 
MATRIX_1 = torch.rand(2, 3)
MATRIX_2 = torch.rand(3, 4)
print(MATRIX_1)
print(MATRIX_2)

torch.matmul(MATRIX_1, MATRIX_2)

tensor([[0.0912, 0.8151, 0.2648],
        [0.8988, 0.3201, 0.5228]])
tensor([[0.6952, 0.2691, 0.6689, 0.7677],
        [0.1456, 0.9015, 0.2138, 0.1805],
        [0.5212, 0.1230, 0.4983, 0.7268]])


tensor([[0.3202, 0.7919, 0.3672, 0.4096],
        [0.9439, 0.5947, 0.9301, 1.1278]])

**Transpose** allows us to flip the axes of matrix 

i.e. (3,2) matrix will be converted in (2,3)

<iframe width="560" height="315" src="https://www.youtube.com/embed/TZrKrNVhbjI?si=T0wQ052ml1UWtTvv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

In [9]:
MATRIX_1

tensor([[0.0912, 0.8151, 0.2648],
        [0.8988, 0.3201, 0.5228]])

In [10]:
MATRIX_1.T

tensor([[0.0912, 0.8988],
        [0.8151, 0.3201],
        [0.2648, 0.5228]])

In [13]:
# find min in matrix
print(MATRIX_1.min())
# find position of min in matrix
print(MATRIX_1.argmin())
# find max in matrix
print(MATRIX_1.max())
# find position of max in matrix
print(MATRIX_1.argmax())
# find mean in matrix
print(MATRIX_1.mean())
# calculate sum of matrix
print(MATRIX_1.sum())


tensor(0.0912)
tensor(0)
tensor(0.8988)
tensor(3)
tensor(0.4855)
tensor(2.9127)


**Reshape** - Reshape allows us to change the shape of matrix.  The only rule is the multiplication of original shape should match with multiplication of reshaped matrix shape.

e.g. - Matrix of shape (2,3) can be reshaped into 
- (3,2)
- (1,6)
- (6,1)

In [28]:
MATRIX_1,MATRIX_1.shape

(tensor([[3.0000, 0.8151, 0.2648],
         [0.8988, 0.3201, 0.5228]]),
 torch.Size([2, 3]))

In [22]:
RESHAPED_MAT = MATRIX_1.reshape(1,6)
print(RESHAPED_MAT)

tensor([[0.0912, 0.8151, 0.2648, 0.8988, 0.3201, 0.5228]])


In [20]:
MATRIX_1.reshape(6,1)

tensor([[0.0912],
        [0.8151],
        [0.2648],
        [0.8988],
        [0.3201],
        [0.5228]])

In [23]:
RESHAPED_MAT[0][0] = 3

In [27]:
RESHAPED_MAT

tensor([[3.0000, 0.8151, 0.2648, 0.8988, 0.3201, 0.5228]])

In [26]:
MATRIX_1

tensor([[3.0000, 0.8151, 0.2648],
        [0.8988, 0.3201, 0.5228]])

*Stacking* Matrices allows us to put matrix on top of each other ( vertical stack ) or by each other's side ( horizontal stack ).
Rule for stacking is that all matrices must be of same dimension

In [43]:
zero_mat = torch.zeros(3,2)
one_mat = torch.ones(3, 2) 
zero_mat.shape, one_mat.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [46]:
vstacked = torch.vstack([zero_mat, one_mat])

vstacked,vstacked.shape

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]),
 torch.Size([6, 2]))

In [48]:
hstacked = torch.hstack([zero_mat, one_mat])
hstacked,hstacked.shape

(tensor([[0., 0., 1., 1.],
         [0., 0., 1., 1.],
         [0., 0., 1., 1.]]),
 torch.Size([3, 4]))

**squeeze** allows us to remove all single dimensions from matrix

In [60]:
tens = torch.zeros(1,3,2,1)
tens

tensor([[[[0.],
          [0.]],

         [[0.],
          [0.]],

         [[0.],
          [0.]]]])

In [61]:
no_one= torch.squeeze(tens)
no_one

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

**unsqueeze** allows us to add  single dimension at specific dim in matrix

In [62]:
no_one, no_one.shape

(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]),
 torch.Size([3, 2]))

In [65]:
adding_one = torch.unsqueeze(no_one, dim=0)
adding_one,adding_one.shape

(tensor([[[0., 0.]],
 
         [[0., 0.]],
 
         [[0., 0.]]]),
 torch.Size([3, 1, 2]))

In [66]:
adding_one = torch.unsqueeze(no_one, dim=1)
adding_one,adding_one.shape

(tensor([[[0., 0.],
          [0., 0.],
          [0., 0.]]]),
 torch.Size([1, 3, 2]))

In [67]:
adding_one = torch.unsqueeze(no_one, dim=2)
adding_one,adding_one.shape

(tensor([[[0.],
          [0.]],
 
         [[0.],
          [0.]],
 
         [[0.],
          [0.]]]),
 torch.Size([3, 2, 1]))

**permute** allows us to rearrange the dimensions of matrix based on the index number of dimesion. 

e.g. If you have a matrix of shape (2,3,4,1) and you want new matrix to be of shape (4,1,3,2) then you'll be putting permute for index numbers as (2,3,1,0) _remember that these are not the dimension numbers but the index numbers of original dimensions_

In [71]:
original_tensor = torch.rand(2,3,4,1)
original_tensor,original_tensor.shape

(tensor([[[[0.4067],
           [0.7352],
           [0.3255],
           [0.2045]],
 
          [[0.9771],
           [0.6874],
           [0.9577],
           [0.5992]],
 
          [[0.3105],
           [0.2828],
           [0.9761],
           [0.0919]]],
 
 
         [[[0.4163],
           [0.2669],
           [0.4095],
           [0.1668]],
 
          [[0.0218],
           [0.2487],
           [0.1014],
           [0.8136]],
 
          [[0.8378],
           [0.0290],
           [0.1106],
           [0.5918]]]]),
 torch.Size([2, 3, 4, 1]))

In [73]:
permuted_tensor = torch.permute(original_tensor,(2,0,3,1))
permuted_tensor,permuted_tensor.shape

(tensor([[[[0.4067, 0.9771, 0.3105]],
 
          [[0.4163, 0.0218, 0.8378]]],
 
 
         [[[0.7352, 0.6874, 0.2828]],
 
          [[0.2669, 0.2487, 0.0290]]],
 
 
         [[[0.3255, 0.9577, 0.9761]],
 
          [[0.4095, 0.1014, 0.1106]]],
 
 
         [[[0.2045, 0.5992, 0.0919]],
 
          [[0.1668, 0.8136, 0.5918]]]]),
 torch.Size([4, 2, 1, 3]))